# Generated by Django 4.1.3 on 2024-10-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gueststay',
            name='guestdetails',
        ),
        migrations.RemoveField(
            model_name='gueststay',
            name='guestidtype',
        ),
        migrations.RemoveField(
            model_name='gueststay',
            name='gueststate',
        ),
        migrations.AddField(
            model_name='gueststay',
            name='guestidtypes',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='guestsdetails',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='gueststates',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
