# Generated by Django 4.1.3 on 2024-10-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_gueststay_guestdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gueststay',
            name='guestidtypes',
        ),
        migrations.RemoveField(
            model_name='gueststay',
            name='guestsdetails',
        ),
        migrations.RemoveField(
            model_name='gueststay',
            name='gueststates',
        ),
    ]
