# Generated by Django 4.1.3 on 2024-10-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rateplanforbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveadvancebookguestdata',
            name='totalguest',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
