# Generated by Django 4.1.3 on 2024-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gueststay_guestidtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='guestidtypes',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='guestsdetails',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='gueststates',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
