# Generated by Django 4.1.3 on 2024-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_saveadvancebookguestdata_totalguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_clean',
            field=models.BooleanField(default=True),
        ),
    ]
