# Generated by Django 4.1.3 on 2024-10-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rooms_is_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookadvance',
            name='totalguest',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
