# Generated by Django 4.1.3 on 2024-10-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_invoicespayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='cash_amount',
            new_name='Due_amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='online_amount',
            new_name='accepted_amount',
        ),
    ]
