# Generated by Django 4.1.3 on 2024-10-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_cash_amount_invoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespayment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
