# Generated by Django 4.1.3 on 2024-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_check_in_time_booking_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(),
        ),
    ]
