# Generated by Django 4.1.3 on 2024-10-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_invoicespayment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_plan_name', models.CharField(max_length=50)),
                ('rate_plan_code', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_person_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_persons', models.PositiveIntegerField(default=1)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='app.roomscategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
