# Generated by Django 4.1.3 on 2024-10-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rateplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='channel',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='rate_plan',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
