# Generated by Django 4.1.3 on 2024-10-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_gueststay_channel_gueststay_rate_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_availibility', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True)),
                ('booked_rooms', models.IntegerField(blank=True, default=0, null=True)),
                ('occupancy', models.IntegerField(blank=True, default=0, null=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roomscategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
