# Generated by Django 4.1.3 on 2024-10-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_segment_booking_totalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advancebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.saveadvancebookguestdata'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gueststay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gueststay'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
