# Generated by Django 4.1.3 on 2024-10-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_advancebook_booking_gueststay_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicespayment',
            name='advancebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.saveadvancebookguestdata'),
        ),
    ]
