# Generated by Django 4.1.3 on 2024-10-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_roomsinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsinventory',
            name='occupancy',
        ),
    ]
