# Generated by Django 4.1.3 on 2024-10-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_invoicespayment_advancebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.invoice'),
        ),
    ]
