# Generated by Django 4.1.3 on 2024-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_invoicespayment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='termscondition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
