# Generated by Django 4.1.3 on 2024-10-23 21:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_vendorcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('book', 'Book'), ('cancel', 'Cancel')], max_length=20)),
                ('hotel_code', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('cm_booking_id', models.CharField(max_length=100)),
                ('booked_on', models.DateTimeField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('segment', models.CharField(max_length=50)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('pah', models.BooleanField(default=False)),
                ('amount_after_tax', models.FloatField()),
                ('amount_before_tax', models.FloatField()),
                ('tax', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MainBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, choices=[('book', 'Book'), ('cancel', 'Cancel'), ('modify', 'modify')], max_length=20, null=True)),
                ('booking_id', models.CharField(max_length=100)),
                ('cm_booking_id', models.CharField(max_length=100)),
                ('booked_on', models.DateTimeField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('segment', models.CharField(max_length=50)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('pah', models.BooleanField(default=False)),
                ('amount_after_tax', models.FloatField()),
                ('amount_before_tax', models.FloatField()),
                ('tax', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('channal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.onlinechannls')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50)),
                ('rateplan_code', models.CharField(max_length=50)),
                ('guest_name', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sell_rate', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='app.room')),
            ],
        ),
        migrations.CreateModel(
            name='MBRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50)),
                ('rateplan_code', models.CharField(max_length=50)),
                ('guest_name', models.CharField(max_length=100)),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('sell_rate', models.FloatField()),
                ('main_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.mainbooking')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='app.address')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app.guest'),
        ),
    ]
