# Generated by Django 4.1.3 on 2024-10-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_hotelprofile_termscondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='loylty_guests_data',
            name='smscount',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
