# Generated by Django 4.1.3 on 2024-10-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_address_booking_mainbooking_room_price_occupancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='occupancy',
            name='room',
        ),
        migrations.RemoveField(
            model_name='price',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Occupancy',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
