# Generated by Django 4.1.3 on 2024-10-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_dynamicpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcm',
            name='dynamic_price_active',
            field=models.BooleanField(default=False),
        ),
    ]
