# Generated by Django 4.1.3 on 2024-11-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rooms_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='is_booked',
        ),
    ]
