# Generated by Django 4.1.3 on 2024-11-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_rooms_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsinventory',
            name='occupancy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomsinventory',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DynamicPricing',
        ),
    ]
