# Generated by Django 4.1.3 on 2024-11-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_roomsinventory_occupancy_roomsinventory_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsinventory',
            old_name='rate',
            new_name='price',
        ),
    ]
