# Generated by Django 4.1.3 on 2024-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_rate_roomsinventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcm',
            name='dynamic_price_plan',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
