# Generated by Django 4.1.3 on 2024-11-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_vendorcm_dynamic_price_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='saveguestid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
