# Generated by Django 4.1.3 on 2024-11-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_travelagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='commission_rate',
            field=models.IntegerField(),
        ),
    ]
