# Generated by Django 4.1.3 on 2024-11-05 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0024_alter_travelagency_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinechannls',
            name='channal_img',
        ),
        migrations.AddField(
            model_name='onlinechannls',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
