# Generated by Django 4.1.3 on 2024-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_hoelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoelimage',
            name='image',
            field=models.ImageField(upload_to='hotel_images'),
        ),
    ]
