# Generated by Django 4.1.3 on 2024-11-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_saveadvancebookguestdata_payment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveadvancebookguestdata',
            name='Payment_types',
            field=models.CharField(blank=True, choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid'), ('partially', 'partially')], max_length=20, null=True),
        ),
    ]
