# Generated by Django 4.1.3 on 2024-11-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_supplierinvoiceitem_remove_purchaseitem_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
