# Generated by Django 4.1.3 on 2024-11-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_supplierinvoiceitem_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amainities',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='MarketIteams',
        ),
        migrations.RemoveField(
            model_name='offerwebsitevendor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offerwebsitevendor',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='reviewqr',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='reviewqr',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='webgallary',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='webreview',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='websitelinks',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendorcm',
            name='channal_manager_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='amainities',
        ),
        migrations.DeleteModel(
            name='offerwebsitevendor',
        ),
        migrations.DeleteModel(
            name='reviewQr',
        ),
        migrations.DeleteModel(
            name='webgallary',
        ),
        migrations.DeleteModel(
            name='webreview',
        ),
        migrations.DeleteModel(
            name='websitelinks',
        ),
    ]
