# Generated by Django 4.1.3 on 2024-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_roomscategory_roomimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcm',
            name='admin_dynamic_active',
            field=models.BooleanField(default=False),
        ),
    ]
