# Generated by Django 4.1.3 on 2024-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_vendorcm_admin_dynamic_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='max_person',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
