# Generated by Django 4.1.3 on 2024-11-23 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0040_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyinvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('Invoicedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companies')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
