# Generated by Django 4.1.3 on 2024-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_companyinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='values',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
