# Generated by Django 4.1.3 on 2024-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_companies_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='childmaxallowed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
