# Generated by Django 4.1.3 on 2024-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rateplan_childmaxallowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='rate_plan_description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
