# Generated by Django 4.1.3 on 2024-11-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0044_rateplan_rate_plan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('quantity', 'Quantity Based Discount'), ('price', 'Price Based Discount')], max_length=10)),
                ('min_quantity', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
