# Generated by Django 4.1.3 on 2024-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_offerbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbe',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
