# Generated by Django 4.1.3 on 2024-11-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_offerbe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerbe',
            name='min_quantity',
        ),
        migrations.RemoveField(
            model_name='offerbe',
            name='offer_type',
        ),
    ]
