# Generated by Django 4.1.3 on 2024-11-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_offerbe_min_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerbe',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
