# Generated by Django 4.1.3 on 2024-12-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_offerbe_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveadvancebookguestdata',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saveadvancebookguestdata',
            name='cm_booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
