# Generated by Django 4.1.3 on 2024-12-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0049_alter_saveadvancebookguestdata_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='beaminities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aminities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
