# Generated by Django 4.1.3 on 2024-12-04 22:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0050_beaminities'),
    ]

    operations = [
        migrations.CreateModel(
            name='becallemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phome', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('guestemail', models.EmailField(blank=True, default=None, max_length=254)),
                ('linkmap', models.URLField(blank=True, default=None)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
