# Generated by Django 4.1.3 on 2024-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_beaminities_cancellention_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveadvancebookguestdata',
            name='is_selfbook',
            field=models.BooleanField(default=False),
        ),
    ]
