# Generated by Django 4.1.3 on 2024-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_saveadvancebookguestdata_is_selfbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaminities',
            name='cancellention_policy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
