# Generated by Django 4.1.3 on 2024-12-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_beaminities_cancellention_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beaminities',
            name='cancellention_policy',
        ),
    ]
