# Generated by Django 4.1.3 on 2024-12-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_bestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestatus',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
