# Generated by Django 4.1.3 on 2024-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_bestatus_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aminitiesinvoiceitem',
            name='hsncode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='aminitiesinvoiceitem',
            name='tax_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
