# Generated by Django 4.1.3 on 2024-12-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_aminitiesinvoiceitem_hsncode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='mdescription',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
