# Generated by Django 4.1.3 on 2024-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_invoiceitem_mdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookadvance',
            name='adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombookadvance',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombookadvance',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roombookadvance',
            name='rateplan_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roombookadvance',
            name='sell_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
