# Generated by Django 4.1.3 on 2024-12-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_roomcleancheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsinventory',
            name='stopsell',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
