# Generated by Django 4.1.3 on 2024-12-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_roomsinventory_stopsell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsinventory',
            name='stopsell',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
