# Generated by Django 4.1.3 on 2024-12-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_roomsinventory_stopsell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsinventory',
            name='stopsell',
        ),
    ]
