# Generated by Django 4.1.3 on 2024-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_remove_roomsinventory_stopsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookadvance',
            name='rateplan_code_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
