# Generated by Django 3.2.20 on 2024-12-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_roombookadvance_rateplan_code_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='is_intvntory',
            field=models.BooleanField(default=False),
        ),
    ]
