# Generated by Django 3.2.20 on 2024-12-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_supplierinvoiceitem_is_intvntory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='salerate',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
