# Generated by Django 3.2.20 on 2024-12-31 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0069_supplierinvoiceitem_salerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='available_qty',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='total_qty',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='itemArrivaldate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('qty', models.BigIntegerField(default=0)),
                ('mainitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.items')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
