# Generated by Django 3.2.20 on 2024-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20241231_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='tax_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
