# Generated by Django 3.2.20 on 2024-12-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_supplierinvoiceitem_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loylty_guests_data',
            name='smscount',
            field=models.IntegerField(default=0),
        ),
    ]
