# Generated by Django 3.2.20 on 2025-01-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_invpermit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invpermit',
            name='room_billing_active',
        ),
    ]
