# Generated by Django 3.2.20 on 2025-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_invoiceitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aminitiesinvoiceitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
