# Generated by Django 3.2.20 on 2025-01-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_aminitiesinvoiceitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
