# Generated by Django 3.2.20 on 2025-01-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_supplierinvoiceitem_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemArrivaldate',
        ),
    ]
