# Generated by Django 4.1.3 on 2025-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='is_cleaner',
            field=models.BooleanField(default=False),
        ),
    ]
