# Generated by Django 5.1.4 on 2025-01-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_savedateblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='paidstatus',
            new_name='is_room',
        ),
    ]
