# Generated by Django 5.1.4 on 2025-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_rename_paidstatus_invoiceitem_is_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookadvance',
            name='checkOutstatus',
            field=models.BooleanField(default=False),
        ),
    ]
