# Generated by Django 5.1.4 on 2025-01-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_roombookadvance_checkoutstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
