# Generated by Django 5.1.4 on 2025-01-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_invoiceitem_is_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedesign',
            name='guestinvcdesign',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoicedesign',
            name='invcdesign',
            field=models.IntegerField(default=1),
        ),
    ]
