# Generated by Django 5.1.4 on 2025-01-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_invoicedesign_guestinvcdesign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
