# Generated by Django 5.1.4 on 2025-01-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_remove_subuser_notification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='ar',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='dp',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='female',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='male',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='transg',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
