# Generated by Django 5.1.4 on 2025-01-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_addcash_cashflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cashFlow',
        ),
    ]
