# Generated by Django 5.1.4 on 2025-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_expensecash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcash',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expensecash',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
