# Generated by Django 5.1.4 on 2025-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_addcash_date_time_alter_expensecash_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecash',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
