# Generated by Django 5.1.4 on 2025-01-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_googlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymanagement',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailymanagement',
            name='totalhours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
