# Generated by Django 5.1.4 on 2025-01-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_dailymanagement_overtime_dailymanagement_totalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymanagement',
            name='overtime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailymanagement',
            name='totalhours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
