# Generated by Django 5.1.4 on 2025-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_alter_dailymanagement_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcm',
            name='inventory_active',
            field=models.BooleanField(default=True),
        ),
    ]
