# Generated by Django 5.1.4 on 2025-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_vendorcm_inventory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicespayment',
            name='maindate',
            field=models.DateField(auto_now=True),
        ),
    ]
