# Generated by Django 5.1.4 on 2025-01-26 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_invoicespayment_maindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespayment',
            name='maindate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
