# Generated by Django 5.1.4 on 2025-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_taxslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxslab',
            name='cgst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='sgst',
            field=models.FloatField(),
        ),
    ]
