# Generated by Django 5.1.4 on 2025-01-28 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_alter_taxslab_cgst_alter_taxslab_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cgst_rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sgst_rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
