# Generated by Django 5.1.4 on 2025-01-28 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_invoiceitem_cgst_rate_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='cgst_rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sgst_rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
