# Generated by Django 5.1.4 on 2025-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_alter_invoiceitem_cgst_rate_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='totalwithouttax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
