# Generated by Django 5.1.4 on 2025-01-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_invoiceitem_totalwithouttax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
