# Generated by Django 5.1.4 on 2025-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_invoice_taxable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_company',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
