# Generated by Django 5.1.4 on 2025-02-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_onlinechannls_company_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='taxableamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
