# Generated by Django 5.1.4 on 2025-02-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_supplierinvoiceitem_taxableamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinvoiceitem',
            name='taxableamount',
        ),
        migrations.CreateModel(
            name='taxSlabpurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_hsnsac_name', models.CharField(blank=True, max_length=15, null=True)),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxableamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.invoice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
