# Generated by Django 5.1.4 on 2025-02-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_remove_supplierinvoiceitem_taxableamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxslabpurchase',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
