# Generated by Django 5.1.4 on 2025-02-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_supplierinvoiceitem_sellinghsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
