# Generated by Django 5.1.4 on 2025-02-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_itempurchasehistorlocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredit',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
