# Generated by Django 5.1.4 on 2025-02-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_customercredit_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
