# Generated by Django 5.1.4 on 2025-02-07 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_purchasepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extraBookingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('csgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roombookadvance')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
