# Generated by Django 5.1.4 on 2025-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_extrabookingamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='extend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='extend_decription',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_extend',
            field=models.BooleanField(default=False),
        ),
    ]
