# Generated by Django 5.1.4 on 2025-02-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_gueststay_extend_gueststay_extend_decription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='created_checkoutdate',
            field=models.DateTimeField(default='2025-2-9', editable=False),
            preserve_default=False,
        ),
    ]
