# Generated by Django 5.1.4 on 2025-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_gueststay_created_checkoutdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
