# Generated by Django 5.1.4 on 2025-02-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_invoiceitem_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='fandbinvoiceid',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
