# Generated by Django 5.1.4 on 2025-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_gueststay_fandbinvoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_fandb',
            field=models.BooleanField(default=False),
        ),
    ]
