# Generated by Django 5.1.4 on 2025-02-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_customguestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fnbinvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.invoice'),
        ),
    ]
