# Generated by Django 5.1.4 on 2025-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_customguestlog_advancebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='values',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
