# Generated by Django 5.1.4 on 2025-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_alter_companies_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='is_ota',
            field=models.BooleanField(default=False),
        ),
    ]
