# Generated by Django 5.1.4 on 2025-02-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_alter_companies_address_alter_companies_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='is_ota',
        ),
    ]
