# Generated by Django 5.1.4 on 2025-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_remove_companies_is_ota'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_ota',
            field=models.BooleanField(default=False),
        ),
    ]
