# Generated by Django 5.1.4 on 2025-02-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_invoiceitem_is_room_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='totalamount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
