# Generated by Django 5.1.4 on 2025-02-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_alter_gueststay_extend_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hourly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hourlyroomsdata'),
        ),
    ]
