# Generated by Django 5.1.4 on 2025-02-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_booking_hourly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hourly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hourlyroomsdata'),
        ),
    ]
