# Generated by Django 5.1.4 on 2025-02-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0143_bulklogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_mealp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='mealpprice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
