# Generated by Django 5.1.4 on 2025-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_invoiceitem_is_mealp_invoiceitem_mealpprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='mealplanname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
