# Generated by Django 5.1.4 on 2025-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0145_invoiceitem_mealplanname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customguestlog',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
