# Generated by Django 5.1.4 on 2025-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_alter_customguestlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespayment',
            name='descriptions',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
