# Generated by Django 5.1.4 on 2025-03-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_alter_invoicespayment_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookpricesdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=False, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('roombook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.roombookadvance')),
            ],
        ),
    ]
