# Generated by Django 5.1.4 on 2025-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_bookpricesdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpricesdates',
            name='date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
