# Generated by Django 5.1.4 on 2025-03-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_alter_bookpricesdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpricesdates',
            name='roombook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.saveadvancebookguestdata'),
        ),
    ]
