# Generated by Django 5.1.4 on 2025-03-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0150_alter_bookpricesdates_roombook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpricesdates',
            name='roombook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.roombookadvance'),
        ),
    ]
