# Generated by Django 5.1.4 on 2025-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0151_alter_bookpricesdates_roombook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='cancellention_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
