# Generated by Django 5.1.4 on 2025-05-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_whatsaap_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsaap_link',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
