# Generated by Django 5.1.4 on 2025-05-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_whatsaap_link_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsaap_link',
            name='active',
        ),
    ]
