# Generated by Django 5.1.4 on 2025-06-08 23:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0159_rooms_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cm_RoomBookAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('bookingguest', models.CharField(max_length=100)),
                ('bookingguestphone', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('totalguest', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('rateplan_code', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('adults', models.PositiveIntegerField(blank=True, null=True)),
                ('children', models.PositiveIntegerField(blank=True, null=True)),
                ('sell_rate', models.FloatField(blank=True, null=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roomscategory')),
                ('saveguestdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saveadvancebookguestdata')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
