# Generated by Django 5.1.4 on 2025-06-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_cm_roombookadvance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cm_roombookadvance',
            name='bookingdate',
        ),
    ]
