# Generated by Django 5.1.4 on 2025-06-09 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0161_remove_cm_roombookadvance_bookingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cm_bookpricesdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('roombook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cm_roombookadvance')),
            ],
        ),
    ]
