# Generated by Django 5.1.4 on 2025-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0162_cm_bookpricesdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm_roombookadvance',
            name='rateplan_code_main',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
