# Generated by Django 5.1.4 on 2025-06-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0165_guest_backid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveadvancebookguestdata',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveadvancebookguestdata',
            name='is_noshow',
            field=models.BooleanField(default=False),
        ),
    ]
