# Generated by Django 5.1.4 on 2025-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0166_saveadvancebookguestdata_is_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomscategory',
            name='is_not_active',
            field=models.BooleanField(default=False),
        ),
    ]
