from django.contrib import admin
from .models import RoomsCategory,Rooms,Taxes,Gueststay,SubscriptionPlan,Subscription
from . models import *
# Register your models here.
admin.site.register(CustomUser)
admin.site.register(Rooms)
admin.site.register(RoomsCategory)
admin.site.register(Taxes)
admin.site.register(Gueststay)
admin.site.register(Subscription)
admin.site.register(SubscriptionPlan)
admin.site.register(onlinechannls)
admin.site.register(RoomBookAdvance)
admin.site.register(loylty_data)
admin.site.register(loylty_Guests_Data)
admin.site.register(Invoice)
admin.site.register(InvoiceItem)
admin.site.register(MoreGuestData)
admin.site.register(SaveAdvanceBookGuestData)
admin.site.register(LaundryServices)
admin.site.register(Employee)
admin.site.register(DailyManagement)
admin.site.register(SalaryManagement)
admin.site.register(Events)
admin.site.register(EventBookGuest)
admin.site.register(HotelProfile)
admin.site.register(Messgesinfo)
admin.site.register(RoomCleaning)
admin.site.register(Items)
admin.site.register(HourlyRoomsdata)
admin.site.register(CustomerCredit)
admin.site.register(Freedemo)
admin.site.register(AminitiesInvoice)
admin.site.register(AminitiesInvoiceItem)
admin.site.register(InvoicesPayment)
admin.site.register(RatePlan)
admin.site.register(RoomsInventory)
admin.site.register(VendorCM)
admin.site.register(RatePlanforbooking)
admin.site.register(Booking)
admin.site.register(RoomImage)
admin.site.register(HoelImage)
admin.site.register(Travelagencyhandling)
admin.site.register(Supplier)
admin.site.register(SupplierInvoiceItem)
admin.site.register(Companies)
admin.site.register(companyinvoice)